from __future__ import annotations

from typing import Any

# (章节标题, 该节指标 key 顺序；未列出的 key 归入「其他」)
QUANT_METRIC_SECTIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "筛股与综合得分",
        (
            "score",
            "score_cheap",
            "score_stability",
            "track",
            "source_strategy",
        ),
    ),
    (
        "行情与估值倍数",
        (
            "price",
            "low_52w",
            "high_52w",
            "drawdown_pct",
            "price_to_low_ratio",
            "pe",
            "pe_ttm",
            "pe_static",
            "pe_dynamic",
            "pb",
            "ps",
            "dividend_yield_pct",
            "industry",
            "market_cap_yuan",
        ),
    ),
    (
        "财报时效（最新一期 vs 最近年报）",
        (
            "financial_data_as_of",
            "financial_reports_count",
            "latest_period_report_date",
            "latest_period_label",
            "has_newer_interim_than_annual",
            "latest_annual_report_date",
            "latest_annual_period_label",
            "current_year_interim_reports",
            "recent_interim_reports",
        ),
    ),
    (
        "商业模式与单元经济（评商业模式时优先看本节）",
        (
            "gross_margin_pct",
            "net_margin_pct",
            "debt_ratio_pct",
            "gross_margin_values",
            "revenue_values",
            "revenue_cagr_3y",
            "net_profit_values",
            "profitable_years_3y",
            "operating_cashflow_values",
            "ocf_to_profit_ratio",
            "ocf_to_profit_ratio_basis",
            "ocf_to_profit_ratio_note",
            "cashflow_quality",
            "latest_revenue",
            "latest_net_profit",
            "latest_operating_cashflow",
            "latest_gross_margin_pct",
            "latest_net_margin_pct",
            "latest_debt_ratio_pct",
            "profitable",
            "roe_values",
            "annual_report_dates_3y",
            "annual_revenue_values_3y",
            "annual_net_profit_values_3y",
            "annual_operating_cashflow_values_3y",
            "latest_annual_revenue",
            "latest_annual_net_profit",
            "latest_annual_operating_cashflow",
            "latest_annual_gross_margin_pct",
            "latest_annual_net_margin_pct",
            "latest_annual_debt_ratio_pct",
        ),
    ),
    (
        "成长性与研发（评成长性时优先看本节）",
        (
            "eps_basic_latest_period",
            "eps_basic_latest_annual",
            "eps_values_3y",
            "eps_values_5y",
            "eps_cagr_3y",
            "eps_cagr_5y",
            "eps_cagr_3y_available",
            "eps_cagr_5y_available",
            "eps_cagr_3y_note",
            "eps_cagr_5y_note",
            "eps_growth_meets_20pct_3y",
            "eps_growth_meets_30pct_3y",
            "rd_expense_yuan",
            "rd_expense_latest_annual",
            "rd_to_revenue_pct",
            "rd_expense_values_3y",
            "rd_to_revenue_pct_values_3y",
            "rd_data_note",
        ),
    ),
    (
        "估值与安全边际（评安全边际时优先看本节）",
        (
            "valuation_default_tier",
            "valuation_fair_pe",
            "valuation_discount_rate",
            "valuation_terminal_growth",
            "valuation_pe_available",
            "valuation_dcf_available",
            "owner_earnings_yuan",
            "owner_earnings_source",
            "intrinsic_value_pe_yuan",
            "intrinsic_price_pe",
            "margin_of_safety_pe_pct",
            "intrinsic_value_dcf_yuan",
            "intrinsic_price_dcf",
            "margin_of_safety_dcf_pct",
            "dcf_next_year_cash_yuan",
            "margin_of_safety_pct",
        ),
    ),
)

METRIC_DESCRIPTIONS: dict[str, str] = {
    "score": "综合得分（0–100），越高表示越符合本策略的便宜+稳定偏好",
    "score_cheap": "便宜度子分（0–1），估值倍数与股息越高越好",
    "score_stability": "财务稳定性子分（0–1），多年收入与利润越稳越高",
    "track": "命中的筛股轨道（如盈利成长、暂亏成长等）",
    "source_strategy": "产生该候选的策略 ID",
    "price": "最新股价（元）",
    "low_52w": "近 52 周最低价（元）",
    "high_52w": "近 52 周最高价（元）",
    "drawdown_pct": "距 52 周高点的回撤幅度（%）",
    "price_to_low_ratio": "现价 ÷ 52 周低点，越接近 1 表示越靠近阶段低位",
    "pe": "主市盈率（优先 TTM，其次动态、静态）",
    "pe_ttm": "滚动市盈率 TTM（近 12 个月利润）",
    "pe_static": "静态市盈率（最近年报利润）",
    "pe_dynamic": "动态市盈率（按最新季报年化预测全年利润）",
    "pb": "市净率（市值 ÷ 净资产）",
    "ps": "市销率（市值 ÷ 营业收入）",
    "dividend_yield_pct": "股息率（%）",
    "industry": "所属行业",
    "market_cap_yuan": "总市值（元）",
    "financial_data_as_of": "财务数据截至日期（最新一份已披露财报）",
    "financial_reports_count": "已纳入分析的财报期数（含季报/年报）",
    "latest_period_report_date": "最新一期财报截止日期",
    "latest_period_label": "最新一期财报类型（如一季报、半年报、年报）",
    "has_newer_interim_than_annual": "是否存在比最近年报更新的季报/半年报",
    "latest_annual_report_date": "最近一份年报截止日期（通常上年 12-31）",
    "latest_annual_period_label": "最近年报标签",
    "current_year_interim_reports": "今年以来已披露的季报/半年报明细列表",
    "recent_interim_reports": "最近几期季报/半年报明细列表",
    "gross_margin_pct": "最新一期销售毛利率（%），单元经济核心：卖一单毛利厚不厚",
    "net_margin_pct": "最新一期销售净利率（%），剔除费用后还能剩多少",
    "debt_ratio_pct": "最新一期资产负债率（%），剥洋葱：高负债时生意能否自转",
    "gross_margin_values": "近 3 年年报毛利率序列（%），看毛利趋势是否一次性拉高",
    "revenue_values": "近 3 年年报营业收入序列（元），看收入是否可持续、可预测",
    "revenue_cagr_3y": "近 3 年年报收入复合增速（%）",
    "net_profit_values": "近 3 年年报净利润序列（元），区分暂亏与先投后赚",
    "profitable_years_3y": "近 3 年年报中盈利的年数",
    "operating_cashflow_values": "近 3 年年报经营现金流净额序列（元），真实现金验证",
    "ocf_to_profit_ratio": "最新一期经营现金流 ÷ 净利润；越高利润越「实」，缺数据为 null",
    "ocf_to_profit_ratio_basis": "ocf_to_profit_ratio 的计算口径（latest_period=最新一期）",
    "ocf_to_profit_ratio_note": "现金流含金量中文说明",
    "cashflow_quality": "现金流质量标签：ocf_covers_profit=现金流能盖住利润；profit_no_ocf=有利润无现金流需警惕；ocf_below_profit=利润偏纸面；both_weak=均弱；loss_positive_ocf=亏损但现金流为正",
    "latest_revenue": "最新一期营业收入（元，可为季报/半年报）",
    "latest_net_profit": "最新一期净利润（元）",
    "latest_operating_cashflow": "最新一期经营现金流净额（元）",
    "latest_gross_margin_pct": "最新一期毛利率（%），同 gross_margin_pct",
    "latest_net_margin_pct": "最新一期净利率（%），同 net_margin_pct",
    "latest_debt_ratio_pct": "最新一期资产负债率（%），同 debt_ratio_pct",
    "profitable": "最新一期是否盈利（净利润>0）",
    "roe_values": "近 3 年年报净资产收益率序列（%）",
    "annual_report_dates_3y": "近 3 年年报日期列表",
    "annual_revenue_values_3y": "近 3 年年报收入序列（元），同 revenue_values",
    "annual_net_profit_values_3y": "近 3 年年报净利润序列（元），同 net_profit_values",
    "annual_operating_cashflow_values_3y": "近 3 年年报经营现金流序列（元），同 operating_cashflow_values",
    "latest_annual_revenue": "最近年报营业收入（元）",
    "latest_annual_net_profit": "最近年报净利润（元）",
    "latest_annual_operating_cashflow": "最近年报经营现金流净额（元）",
    "latest_annual_gross_margin_pct": "最近年报毛利率（%）",
    "latest_annual_net_margin_pct": "最近年报净利率（%）",
    "latest_annual_debt_ratio_pct": "最近年报资产负债率（%）",
    "eps_basic_latest_period": "最新一期基本每股收益（元/股，可为季报）",
    "eps_basic_latest_annual": "最近年报基本每股收益（元/股）",
    "eps_values_3y": "近 3 年年报 EPS 序列（元/股），用于持续增长型参考",
    "eps_values_5y": "近 5 年年报 EPS 序列（元/股）",
    "eps_cagr_3y": "近 3 年年报 EPS 复合增速（%）；含亏损年份时不计算",
    "eps_cagr_5y": "近 5 年年报 EPS 复合增速（%）；含亏损年份时不计算",
    "eps_cagr_3y_available": "近 3 年 EPS 复合增速是否可算（全为正且数据齐）",
    "eps_cagr_5y_available": "近 5 年 EPS 复合增速是否可算",
    "eps_cagr_3y_note": "EPS 增速不可算时的说明",
    "eps_cagr_5y_note": "EPS 5 年增速不可算时的说明",
    "eps_growth_meets_20pct_3y": "近 3 年 EPS 复合增速是否≥20%（仅当可算时；供持续增长型参考）",
    "eps_growth_meets_30pct_3y": "近 3 年 EPS 复合增速是否≥30%（仅当可算时）",
    "rd_expense_yuan": "最新一期研发费用（元）",
    "rd_expense_latest_annual": "最近年报研发费用（元）",
    "rd_to_revenue_pct": "最新一期研发费用占收入比例（%）",
    "rd_expense_values_3y": "近 3 年年报研发费用序列（元）",
    "rd_to_revenue_pct_values_3y": "近 3 年年报研发占收入比例序列（%）",
    "rd_data_note": "研发费用缺失说明",
    "valuation_default_tier": "默认估值档位 ID（安全边际打分时可先参考，再选更契合档位）",
    "valuation_fair_pe": "默认档合理市盈率假设",
    "valuation_discount_rate": "默认档 DCF 折现率",
    "valuation_terminal_growth": "默认档 DCF 永续增长率",
    "valuation_pe_available": "是否可算 PE 法合理市值",
    "valuation_dcf_available": "是否可算简易 DCF 合理市值",
    "owner_earnings_yuan": "股东盈余（元），优先取经营现金流否则取净利润",
    "owner_earnings_source": "股东盈余来源：operating_cashflow 或 net_profit",
    "intrinsic_value_pe_yuan": "PE 法合理总市值（元，默认档）",
    "intrinsic_price_pe": "PE 法合理股价（元，默认档）",
    "margin_of_safety_pe_pct": "PE 法安全边际（%）；>0 表示低于合理价，<0 表示偏贵",
    "intrinsic_value_dcf_yuan": "DCF 法合理总市值（元，默认档）",
    "intrinsic_price_dcf": "DCF 法合理股价（元，默认档）",
    "margin_of_safety_dcf_pct": "DCF 法安全边际（%）",
    "dcf_next_year_cash_yuan": "DCF 模型假设的次年现金流（元）",
    "margin_of_safety_pct": "综合安全边际（%），PE 与 DCF 中取更保守者",
}

VALUATION_TIER_FIELD_LABELS: dict[str, str] = {
    "fair_pe": "合理 PE 假设",
    "discount_rate": "折现率",
    "terminal_growth": "永续增长率",
    "margin_of_safety_pe_pct": "PE 安全边际（%）",
    "margin_of_safety_dcf_pct": "DCF 安全边际（%）",
    "margin_of_safety_pct": "综合 MOS（%）",
    "intrinsic_price_pe": "合理股价（PE 法，元）",
    "intrinsic_price_dcf": "合理股价（DCF 法，元）",
    "intrinsic_value_pe_yuan": "合理总市值（PE 法，元）",
    "intrinsic_value_dcf_yuan": "合理总市值（DCF 法，元）",
}


def metric_description(key: str) -> str:
    return METRIC_DESCRIPTIONS.get(key, "程序计算的量化字段")


def format_metric_line(key: str, value: Any) -> str:
    return f"- {key}: {value}  — {metric_description(key)}"


def group_metric_keys(metrics: dict[str, Any]) -> list[tuple[str, list[str]]]:
    remaining = {key for key in metrics if key != "valuation_tiers"}
    grouped: list[tuple[str, list[str]]] = []

    for title, keys in QUANT_METRIC_SECTIONS:
        section_keys = [key for key in keys if key in remaining]
        if section_keys:
            grouped.append((title, section_keys))
            remaining -= set(section_keys)

    if remaining:
        grouped.append(("其他", sorted(remaining)))
    return grouped
